# Generated by Django 4.1 on 2022-08-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='login',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='login',
            name='id',
        ),
        migrations.RemoveField(
            model_name='login',
            name='name',
        ),
        migrations.RemoveField(
            model_name='login',
            name='price',
        ),
        migrations.AddField(
            model_name='login',
            name='address',
            field=models.CharField(max_length=220, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='country',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='email_id',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='first_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='last_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='phone_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='registration_number',
            field=models.CharField(default=None, max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='login',
            table='LOGIN_CREDENTIALS',
        ),
    ]
