# Generated by Django 4.1 on 2022-09-02 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0002_alter_login_options_remove_login_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='address',
            new_name='address_id',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='registration_number',
            new_name='registration_num',
        ),
    ]
