# Generated by Django 4.1 on 2022-09-02 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0003_rename_address_login_address_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='country',
        ),
    ]
