# Generated by Django 4.1 on 2022-09-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginpage', '0004_remove_login_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='email_id',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='phone_num',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='registration_num',
            field=models.CharField(default=None, max_length=30, primary_key=True, serialize=False, unique=True),
        ),
    ]
